# Generated by Django 2.1 on 2019-06-15 11:20

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolumler',
            fields=[
                ('bolum_adi', models.CharField(max_length=20)),
                ('bolum_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Dersler',
            fields=[
                ('ders_adi', models.CharField(max_length=25)),
                ('ders_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('bolum_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ogrenci.Bolumler')),
            ],
        ),
        migrations.CreateModel(
            name='Notlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puan', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('ders_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ogrenci.Dersler')),
            ],
        ),
        migrations.CreateModel(
            name='Ogrenci',
            fields=[
                ('isim', models.CharField(max_length=15)),
                ('soyisim', models.CharField(max_length=25)),
                ('ogrenci_id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('bolum_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ogrenci.Bolumler')),
            ],
        ),
        migrations.AddField(
            model_name='notlar',
            name='ogrenci_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ogrenci.Ogrenci'),
        ),
    ]
