# Generated by Django 2.2.2 on 2019-06-17 07:12

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bolumler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bolum_adi', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Dersler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ders_adi', models.CharField(max_length=25)),
                ('bolum_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ogrenci.Bolumler')),
            ],
        ),
        migrations.CreateModel(
            name='Ogrenci',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=15)),
                ('soyisim', models.CharField(max_length=25)),
                ('bolum_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ogrenci.Bolumler')),
            ],
        ),
        migrations.CreateModel(
            name='Notlar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('puan', models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('ders_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ogrenci.Dersler')),
                ('ogrenci_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ogrenci.Ogrenci')),
            ],
        ),
    ]
