# Generated by Django 2.2.2 on 2019-06-18 06:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogrenci', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dersler',
            old_name='bolum_id',
            new_name='bolum',
        ),
        migrations.RenameField(
            model_name='notlar',
            old_name='ders_id',
            new_name='dersler',
        ),
        migrations.RenameField(
            model_name='notlar',
            old_name='ogrenci_id',
            new_name='ogrenci',
        ),
        migrations.RenameField(
            model_name='ogrenci',
            old_name='bolum_id',
            new_name='bolum',
        ),
        migrations.AlterField(
            model_name='notlar',
            name='puan',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(1000), django.core.validators.MinValueValidator(10)]),
        ),
    ]
