# Generated by Django 2.2.2 on 2019-06-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogrenci', '0002_auto_20190618_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dersler',
            name='ders_adi',
            field=models.CharField(max_length=50),
        ),
    ]
