# Generated by Django 2.2.2 on 2019-06-18 10:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ogrenci', '0004_ogrenci_telefon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogrenci',
            name='telefon',
            field=models.CharField(max_length=19, null=True, validators=[django.core.validators.RegexValidator('^\\+(\\d{2})\\s\\((\\d{3})\\)\\s(\\d{3})\\s(\\d{2})\\s(\\d{2})', message='Telefon istenilen formatta değil')]),
        ),
    ]
