# Generated by Django 2.2.2 on 2019-06-18 10:54

from django.db import migrations, models
import ogrenci.models.ogrenci


class Migration(migrations.Migration):

    dependencies = [
        ('ogrenci', '0005_auto_20190618_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogrenci',
            name='telefon',
            field=models.CharField(max_length=19, null=True, validators=[ogrenci.models.ogrenci.validate_telefon]),
        ),
    ]
