# Generated by Django 2.2.2 on 2019-06-20 12:53

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ogrenci', '0006_auto_20190618_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dersler',
            name='bolum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolum', to='ogrenci.Bolumler'),
        ),
        migrations.AlterField(
            model_name='notlar',
            name='puan',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='ogrenci',
            name='telefon',
            field=models.CharField(max_length=19, null=True, validators=[django.core.validators.RegexValidator(regex='^\\+(\\d{2})\\s\\((\\d{3})\\)\\s(\\d{3})\\s(\\d{2})\\s(\\d{2})')]),
        ),
    ]
