# Generated by Django 2.2.2 on 2019-06-20 13:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ogrenci', '0007_auto_20190620_1253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ogrenci',
            name='bolum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bolum_ogrenci', to='ogrenci.Bolumler'),
        ),
    ]
